[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyScriptForHardisGroup"
version = "1.0"
authors = [{name = "Thomas Prezot", email = "thomas@example.com"}]
